[package]
name = "ricevm-loader"
description = "The binary format parser for RiceVM bytecode"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
publish = false
license.workspace = true

[dependencies]
ricevm_core.workspace = true
tracing.workspace = true
